# Generated by Django 5.2.6 on 2025-10-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL имя')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'группы',
                'verbose_name_plural': 'группы',
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'статьи', 'verbose_name_plural': 'статьи'},
        ),
    ]
