# Generated by Django 5.2.6 on 2025-10-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_group_alter_article_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('description', models.TextField(blank=True, default='', max_length=255, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'категории',
                'verbose_name_plural': 'категорию',
            },
        ),
    ]
