# Generated by Django 5.2.7 on 2025-10-25 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='клиенты')),
                ('last_name', models.CharField(max_length=30, verbose_name='клиенты')),
            ],
            options={
                'verbose_name': 'клиенты',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категорию', 'verbose_name_plural': 'категории'},
        ),
    ]
