# Generated by Django 5.2.7 on 2025-11-02 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Тему', 'verbose_name_plural': 'Темы'},
        ),
        migrations.AlterField(
            model_name='topic',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.CharField(max_length=300, verbose_name='Текст'),
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Информация')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.topic')),
            ],
            options={
                'verbose_name': 'Информацию',
                'verbose_name_plural': 'Информация',
            },
        ),
    ]
