# Generated by Django 5.2.7 on 2025-10-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('date', models.DateTimeField(verbose_name='дата')),
                ('content', models.TextField(verbose_name='содержание')),
                ('status', models.IntegerField(verbose_name='статус')),
            ],
        ),
    ]
